name = FrontPage
description = TibebTube Front page layout. It contains header, content and footer without any sidebars.
template = frontpage-layout

;regions
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

;style
stylesheets[all][]= css/layout/front/frontpage.layout.css
stylesheets[all][]= css/layout/front/frontage.layout.no-query.css


